### ISSUE TITLE
- and _ have bad spacing

### ISSUE THREAD

**Issue by andiandi13** [sursly/katahdin#3]
![2022-03-19 11_58_30-hyphen à 45 de KatahdinRound-Bold HYPHEN-MINUS](https://user-images.githubusercontent.com/19387072/159118295-79e2e8d6-1a6d-4b22-8e1d-3684c99aaa60.png)
![2022-03-19 11_58_37-_ 025 ass - Aegisub 9214, Daydream Cafe Edition  Shinon](https://user-images.githubusercontent.com/19387072/159118298-39008201-e1b6-4cf4-aeb3-931aa890b04a.png)

**Comment by sursly** [comment]
Just corrected this with a new build, thanks for the catch!
